-- Local database definition.

DROP DATABASE IF EXISTS local_db;

CREATE DATABASE local_db;

USE local_db;

DROP TABLE IF EXISTS PERSONS;
DROP TABLE IF EXISTS POSTS;

CREATE TABLE IF NOT EXISTS PERSONS (
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    USERNAME VARCHAR (127) NOT NULL UNIQUE,
    PASSWORD VARCHAR (127) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS POSTS (
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    PERSON_ID INT NOT NULL,
    TITLE VARCHAR (127) NOT NULL UNIQUE,
    BODY VARCHAR (127) NOT NULL,
    VIEWS INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON FOREIGN KEY (PERSON_ID)  
    REFERENCES PERSON(ID)  
    ON DELETE CASCADE  
    ON UPDATE CASCADE  
);