// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Credentials struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

type Person struct {
	ID        float64 `json:"id"`
	Username  string  `json:"username"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	Posts     []*Post `json:"posts"`
}

type PersonValidationErrors struct {
	Errors []string `json:"errors"`
}

type PersonValidationObject struct {
	Person           *Person                 `json:"person"`
	ValidationErrors *PersonValidationErrors `json:"validationErrors"`
}

type Post struct {
	ID        float64 `json:"id"`
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	Views     int     `json:"views"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	PersonID  string  `json:"personId"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}
