// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Credentials struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

type Person struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type PersonValidationObject struct {
	Person           *Person           `json:"person"`
	ValidationErrors *ValidationErrors `json:"validationErrors"`
}

type Post struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	Views     int     `json:"views"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	Person    *Person `json:"person"`
}

type PostInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type PostValidationObject struct {
	Post   *Post             `json:"post"`
	Token  string            `json:"token"`
	Errors *ValidationErrors `json:"errors"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type ValidationErrors struct {
	Errors []string `json:"errors"`
}
