

CREATE TABLE IF NOT EXISTS PERSONS (
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    USERNAME VARCHAR (127) NOT NULL UNIQUE,
    PASSWORD VARCHAR (127) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);