
CREATE TABLE IF NOT EXISTS POSTS (
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    PERSON_ID INT NOT NULL,
    TITLE VARCHAR (127) NOT NULL UNIQUE,
    BODY VARCHAR (127) NOT NULL,
    VIEWS INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON FOREIGN KEY (PERSON_ID)  
    REFERENCES PERSONS(ID)  
    ON DELETE CASCADE  
    ON UPDATE CASCADE
);